### PR TITLE
Add CSharp naming styles

### PR DESCRIPTION
**Pull request by matiasbeckerle**
## Background

C# style guide is on progress, we need to define all the styles we use.

## Changes

- Added C# naming styles.

## Notes

I don't particularly like the constants default style from Microsoft. Opinions?

### CODE REVIEW

**Comment by andresmoschini** [comment]
I also like uppercase for constants, but it seems that Microsoft _cool teams_ are using pascal case, for example: https://github.com/aspnet/Mvc/blob/ca017eced27a0493eed7cec443991795ddfadf17/src/Microsoft.AspNetCore.Mvc.TagHelpers/FormActionTagHelper.cs#L44

In old examples they were using camel case: https://msdn.microsoft.com/en-us/library/ms173119(v=vs.80).aspx

**Comment by matiasbeckerle** [comment]
Thanks @AlphaGit! Exactly, as @andresmoschini mentioned they use `PascalCase` for constants (which I also add the style here).

I'm putting on the table using `SCREAMING_CASE` because it's easy to recognize inside a class and to distinguish between public properties and other type of members. Ideas, opinions? Do you like `PascalCase` for constants? Do you prefer `SCREAMING_CASE`? (I'm asking to all) Shoot!

**Comment by Abriscioli** [comment]
I prefer `UPER_CASE` or `SCREAMING_CASE` for constants

**Comment by mvazquez-ms** [comment]
+1 to `PascalCase` because it's MSFT standard, and I always prefer to comply with the standard unless there's a good reason to go against it. This is just a matter of taste, IMO.

As @AlphaGit said:

> I don't see benefits one way or another,

Constants being 'recognizable' doesn't seem to be a compelling reason to me, otherwise Hungarian notation will still be around. Same reasoning as `var` vs explicit, 99.99% of the time, making it explicit is nothing but noise.

Having said that, I'm OK with whatever you chose, buy my preference is with `PascalCase`

**Comment by matiasbeckerle** [comment]
Ok going to leave the Microsoft's standard for constants until we have more arguments to do otherwise. Thanks all for the feedback!

**Pull request merged**
