### PR TITLE
[NoTicket] Swift Style Guide

### PR DESCRIPTION
**Pull request by mvazquez-ms**
## Background

Created Swift Style guide, based on Ray Wenderlich's guide, slightly modified to fit our conventions.

[Here's ](https://github.com/MakingSense/code-style-guides/tree/SwiftStyleGuide/Swift)the preview if you don't want to read the markdown version.

## Required reviewers

@lpelizzaMS
@jsmuguruza 
@mmaldini33
@bsztamfater-ms 

## Optional reviewers

@mravinale 
@AlphaGit 
@matiasbeckerle 

@mravinale , can you check if the mobile guys are part of this team? I cannot add them as reviewers.

### CODE REVIEW

**Comment by mravinale** [comment]
@mvazquez-ms added the mobile team!

@lpelizzaMS
@jsmuguruza
@mmaldini33
@bsztamfater-ms

**Comment by jsmuguruza** [comment]
Quick question @mvazquez-ms in this case:

Preferred:

let width = 120.0                                    // Double
let widthString = (width as NSNumber).stringValue    // String
Not Preferred:

let width: NSNumber = 120.0                          // NSNumber
let widthString: NSString = width.stringValue        // NSString

Wouldn't 

let width: Double = 120.0                                    // Double
let widthString: String = (width as NSNumber).stringValue    // String

Be a better preferred example? because the comparison it's clearly saying that using NS classes is not preferred but not saying anything about explicitly declaring the variable's class.

**Comment by mvazquez-ms** [comment]
>Quick question @mvazquez-ms in this case:
>
>Preferred:
>
>let width = 120.0 // Double
>let widthString = (width as NSNumber).stringValue // String
>Not Preferred:
>
>let width: NSNumber = 120.0 // NSNumber
>let widthString: NSString = width.stringValue // NSString
>
>Wouldn't
>
>let width: Double = 120.0 // Double
>let widthString: String = (width as NSNumber).stringValue // String
>
>Be a better preferred example? because the comparison it's clearly saying that using NS classes is not >preferred but not saying anything about explicitly declaring the variable's class.

I think you are mixing two things here..

First, type inference:

> let width: Double = 120.0 // Double

That wouldn't comply with our guidelines, since type inference is always recommended except for collections. So the correct way would be:

`let width = 120.0 // Double`

Second, because of type inference, in you example, specifying the type is meaningless, it doesn't change anything. In the 'not preferred' approach, there's an implicit cast to NSNumber.

**Comment by jsmuguruza** [comment]
@mvazquez-ms  I see, you're right!

BTW; there wasn't a way to actually reply a comment? I had to make a new comment... anyways.

I will now approve the PR so you can merge.

**Pull request merged**
